version: '3.7'
services:
  verisense_1:
    image: miketang84/verisense:20241022
    # image: verisense
    restart: always
    ports:
      - "9944:9944"
      - "30333:30333"
    environment:
      - RUST_LOG=info
    command: verisense --dev --base-path ./data --rpc-external
    # volumes:
    #   - ./substrate-data:/verisense/data
    
  meilisearch_1:
    image: miketang84/meilisearch:20241022
    restart: always
    ports:
      - "7700:7700"
    command: meilisearch --master-key 123456 --http-addr 0.0.0.0:7700

  surrogate_1:
    image: miketang84/surrogate:20241022
    restart: always
    command: surrogate
    depends_on:
      - verisense_1
      - meilisearch_1
