version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/tmp/nginx.conf
      - ./conf/entrypoint.sh:/usr/local/bin/entrypoint.sh
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh
    depends_on:
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:latest
    command: ["meilisearch", "--master-key", "${MEILI_MASTER_KEY}", "--experimental-enable-containsFilter"]
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  vesync:
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      meilisearch:
        condition: service_healthy
