[package]
name = "vemodel"
version = "0.1.0"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }
serde = { workspace = true }
vrs-core-sdk = { workspace = true }
sha2 = { version = "0.10", default-features = false }
hex = "0.4"

[features]
std = [
    "vrs-core-sdk/std"
]
